document.writeln("<!-- footer-start -->");
document.writeln("    <div id=\'fd\' class=\'index-fd pr\'>");
document.writeln("        <div class=\'map-bg3\'></div>");
document.writeln("        <div class=\'wp\'>");
document.writeln("            <div class=\'fd-top\'>");
document.writeln("                <dl>");
document.writeln("                    <dt>关于我们</dt>");
document.writeln("                    <dd>");
document.writeln("                        <ul class=\'ul-fd\'>");
document.writeln("                            <li><a href=\'about.html\'>我们是谁</a></li>");
document.writeln("                            <li><a href=\'about.html\'>我们提供什么服务</a></li>");
document.writeln("                            <li><a href=\'about.html\'>我们服务的客户</a></li>");
document.writeln("                            <li><a href=\'about.html\'>我们的团队</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("                <dl>");
document.writeln("                    <dt>服务项目</dt>");
document.writeln("                    <dd>");
document.writeln("                        <ul class=\'ul-fd\'>");
document.writeln("                            <li><a href=\'service.html\'>网站建设</a></li>");
document.writeln("                            <li><a href=\'service.html\'>H5响应式 交互网站</a></li>");
document.writeln("                            <li><a href=\'service.html\'>移动端 & 微网站定制</a></li>");
document.writeln("                            <li><a href=\'service.html\'>服务流程</a></li>");
document.writeln("                            <li><a href=\'service.html\'>行业解决方案</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("                <dl>");
document.writeln("                    <dt>案例展示</dt>");
document.writeln("                    <dd>");
document.writeln("                        <ul class=\'ul-fd\'>");
document.writeln("                            <li><a href=\'case.html\'>平台电商</a></li>");
document.writeln("                            <li><a href=\'case.html\'>HTML5</a></li>");
document.writeln("                            <li><a href=\'case.html\'>企业网站</a></li>");
document.writeln("                            <li><a href=\'case.html\'>集团公司</a></li>");
document.writeln("                            <li><a href=\'case.html\'>加工制造</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("                <dl>");
document.writeln("                    <dt>友情链接</dt>");
document.writeln("                    <dd>");
document.writeln("                        <ul class=\'ul-fd\'>");
document.writeln("                            <li><a target='_blank' href=\'http://www.jastar-wang.com\'>代码与酒</a></li>");
document.writeln("                            <li><a target='_blank' href=\'https://gitee.com/jastar-wang\'>码云</a></li>");
document.writeln("                            <li><a target='_blank' href=\'http://www.aliyun.com\'>阿里云</a></li>");
document.writeln("                            <li><a target='_blank' href=\'http://su.baidu.com/\'>百度云CDN</a></li>");
document.writeln("                            <li><a target='_blank' href=\'http://www.alibabagroup.com/cn/global/home?spm=5176.8142029.631162.d8001.e9396d3eiLHMDu\'>阿里巴巴集团</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("                <dl>");
document.writeln("                    <dt>联系我们</dt>");
document.writeln("                    <dd class=\'pr\'>");
document.writeln("                        <p>");
document.writeln("                              <img width='40' src='images/side_icon01.png' style='vertical-align:middle;' /> ");
document.writeln("                              <span style=\'font-size:15px;vertical-align:middle;color:#a8a8af;\'>1152241429（王先生）</span>");
// document.writeln("                            <a href=\'\' class=\'weixin\'></a>");
// document.writeln("                            <a href=\'\' class=\'sina\'></a>");
// document.writeln("                            <span class=\'weixin-pic\'><img src=\'images/ewm.jpg\' alt=\'\'></span>");
document.writeln("                        </p>");
document.writeln("                        <p>");
document.writeln("                              <img width='40' src='images/side_icon03.png' style='vertical-align:middle;' /> ");
document.writeln("                              <span style=\'font-size:15px;vertical-align:middle;color:#a8a8af;\'>131****0205（王先生）</span>");
document.writeln("                        </p>");
document.writeln("                    </dd>");
document.writeln("                </dl>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'fd-copy\'>");
document.writeln("            <div class=\'wp\'>");
document.writeln("                <p>");
document.writeln("                    <span>北创软件工作室（北京） Copyright &copy; 2016-2018 </span>");
document.writeln("                    <span> 丨 京ICP备17038845号</span>");
document.writeln("                    <span> 丨 请认准唯一官方网站 http://studio.jastar-wang.com</span>");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'side\'>");
document.writeln("        <ul>");
document.writeln("            <li>");
document.writeln("                <a href=\'javascript:;\'>");
document.writeln("                    <div class=\'sidebox\'><img src=\'images/side_icon02.png\'>在线咨询</div>");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a target=\'_blank\' href=\'http://sighttp.qq.com/authd?IDKEY=c23f47d2126252738339c4e52e31083c0e800552311b5464\'>");
document.writeln("                    <div class=\'sidebox\'><img src=\'images/side_icon01.png\'>QQ咨询</div>");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'javascript:;\'>");
document.writeln("                    <div class=\'sidebox\'><img src=\'images/side_icon03.png\'>131****0205</div>");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("    <div class=\'side2\'>");
document.writeln("        <ul>");
document.writeln("            <li>");
document.writeln("                <a href=\'\'><img src=\'images/r_icon1.png\' alt=\'\'></a>");
document.writeln("                <div class=\'weixin\' style='right:41px;'><em></em><img src=\'images/ewm.jpg\' alt=\'\'></div>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'javascript:goTop();\' class=\'sidetop\'><img src=\'images/r_icon2.png\'></a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("    <!-- footer-end -->");